# Generated by Django 6.0.4 on 2026-05-19 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='mobile')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='department')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='status')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
